# Generated by Django 3.2.9 on 2022-05-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wxauth', '0002_auto_20220427_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='hfwxuser',
            name='can_add',
            field=models.BooleanField(default=False),
        ),
    ]
