# Generated by Django 3.2.9 on 2022-04-29 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_session', models.CharField(max_length=255)),
                ('rq', models.DateField()),
                ('yh', models.CharField(max_length=10)),
                ('sbhxt', models.CharField(max_length=255)),
                ('tzr', models.CharField(max_length=10)),
                ('gzxxhyy', models.TextField()),
                ('clkssj', models.TimeField()),
                ('clgcsm', models.TextField()),
                ('cljssj', models.TimeField()),
                ('jqfx', models.TextField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkbookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='workbook/')),
                ('workbook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='outsourcingManagement.workbook')),
            ],
        ),
    ]
