# Generated by Django 3.2.9 on 2022-05-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outsourcingManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workbook',
            name='wx_username',
            field=models.CharField(default='陈永平', max_length=10),
            preserve_default=False,
        ),
    ]
