# Generated by Django 3.2.9 on 2021-11-17 02:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempInto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weixinID', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=10)),
                ('iccard', models.CharField(max_length=18)),
                ('healthValue', models.PositiveSmallIntegerField(choices=[(0, '绿码'), (1, '非绿码')], default=0)),
                ('daysValue', models.PositiveSmallIntegerField(choices=[(0, '1天'), (1, '2天'), (2, '3天')], default=0)),
                ('outProvinceValue', models.PositiveSmallIntegerField(choices=[(0, '未出过省'), (1, '出过省')], default=0)),
                ('outCompany', models.CharField(max_length=255)),
                ('project', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(max_length=10)),
                ('contactPhone', models.CharField(max_length=11)),
                ('createtime', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待处理'), (1, '找不到对应联系人'), (2, '已提交审批流程'), (3, '通过'), (4, '拒绝')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TempintoFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='covid19/')),
                ('tempinto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covidform.tempinto')),
            ],
        ),
    ]
