# Generated by Django 3.2.9 on 2021-11-18 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinto',
            name='reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tempinto',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, '待处理'), (1, '找不到对应联系人'), (2, '已生成申请单'), (3, '审批中'), (4, '通过'), (5, '拒绝'), (6, '已删除')], default=0),
        ),
    ]
