# Generated by Django 3.2.9 on 2021-11-23 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0002_auto_20211118_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempinto',
            name='daysValue',
            field=models.PositiveSmallIntegerField(choices=[(1, '1天'), (2, '2天'), (3, '3天')], default=1),
        ),
        migrations.AlterField(
            model_name='tempinto',
            name='healthValue',
            field=models.PositiveSmallIntegerField(choices=[(1, '绿码'), (0, '非绿码')], default=1),
        ),
        migrations.AlterField(
            model_name='tempintofile',
            name='tempinto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='covidform.tempinto'),
        ),
    ]
