# Generated by Django 3.2.9 on 2021-12-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0005_auto_20211203_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='overtimeinto',
            name='gateValue',
            field=models.PositiveSmallIntegerField(choices=[(1, '一号门'), (2, '厂前区')], default=1),
        ),
    ]
