# Generated by Django 3.2.9 on 2022-05-06 21:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('covidform', '0007_alter_overtimeinto_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clrc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wx_session', models.CharField(max_length=255)),
                ('gcmc', models.CharField(max_length=255)),
                ('sgdw', models.CharField(max_length=255)),
                ('jhjcksrq', models.DateField()),
                ('jhjcjsrq', models.DateField()),
                ('cx', models.CharField(max_length=20)),
                ('cphm', models.CharField(max_length=10)),
                ('tssgcl', models.PositiveSmallIntegerField(choices=[(0, '否'), (1, '是')], default=0)),
                ('jsy', models.CharField(max_length=10)),
                ('sqly', models.TextField()),
                ('dclxrxm', models.CharField(max_length=10)),
                ('dclxrsj', models.CharField(max_length=11)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待处理'), (1, '找不到联系人'), (2, '已生成申请单'), (3, '审批中'), (4, '通过'), (5, '删除')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ClrcFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='clrc/')),
                ('clrc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='covidform.clrc')),
            ],
        ),
    ]
